#include "Platforms.h"


namespace Platforms {

static const QHash<Id, QString> short_names = {
    { THREEDO, "3do" },
    { AMIGA, "amiga" },
    { AMSTRAD_CPC, "amstradcpc" },
    { APPLE_II, "apple2" },
    { ARCADE, "arcade" },
    { ATARI_2600, "atari2600" },
    { ATARI_5200, "atari5200" },
    { ATARI_7800, "atari7800" },
    { ATARI_800, "atari800" },
    { ATARI_JAGUAR, "atarijaguar" },
    { ATARI_JAGUAR_CD, "atarijaguarcd" },
    { ATARI_LYNX, "atarilynx" },
    { ATARI_ST, "atarist" },
    { ATARI_XE, "atarixe" },
    { COLECOVISION, "colecovision" },
    { COMMODORE_64, "c64" },
    { INTELLIVISION, "intellivision" },
    { MAC_OS, "macintosh" },
    { MSX, "msx" },
    { NEOGEO, "neogeo" },
    { NEOGEO_POCKET, "ngp" },
    { NEOGEO_POCKET_COLOR, "ngpc" },
    { NINTENDO_3DS, "n3ds" },
    { NINTENDO_64, "n64" },
    { NINTENDO_DS, "nds" },
    { NINTENDO_GAMECUBE, "ngc" },
    { NINTENDO_GAME_BOY, "gb" },
    { NINTENDO_GAME_BOY_ADVANCE, "gba" },
    { NINTENDO_GAME_BOY_COLOR, "gbc" },
    { NINTENDO_NES, "nes" },
    { NINTENDO_SNES, "snes" },
    { NINTENDO_SWITCH, "switch" },
    { NINTENDO_WII, "wii" },
    { NINTENDO_WII_U, "wiiu" },
    { PC, "pc" },
    { PLAYSTATION, "psx" },
    { PLAYSTATION_2, "ps2" },
    { PLAYSTATION_3, "ps3" },
    { PLAYSTATION_4, "ps4" },
    { PLAYSTATION_PORTABLE, "psp" },
    { PLAYSTATION_VITA, "psvita" },
    { SEGA_32X, "sega32x" },
    { SEGA_CD, "segacd" },
    { SEGA_DREAMCAST, "dreamcast" },
    { SEGA_GAME_GEAR, "gamegear" },
    { SEGA_GENESIS, "genesis" },
    { SEGA_MASTER_SYSTEM, "mastersystem" },
    { SEGA_MEGA_DRIVE, "megadrive" },
    { SEGA_SATURN, "saturn" },
    { TURBOGRAFX_16, "pcengine" },
    { WONDERSWAN, "wonderswan" },
    { WONDERSWAN_COLOR, "wonderswancolor" },
    { XBOX, "xbox" },
    { XBOX_360, "xbox360" },
    { XBOX_ONE, "xboxone" },
    { ZX_SPECTRUM, "zxspectrum" },
};

QString shortName(Id id) {
    return short_names.value(id, "");
}

Id idFromShortName(const QString& name) {
    return short_names.key(name, Platforms::Id::UNKNOWN);
}

const QHash<Id, QString> long_names = {
    { THREEDO, "3DO" },
    { AMIGA, "Amiga" },
    { AMSTRAD_CPC, "Amstrad CPC" },
    { APPLE_II, "Apple II" },
    { ARCADE, "Arcade" },
    { ATARI_2600, "Atari 2600" },
    { ATARI_5200, "Atari 5200" },
    { ATARI_7800, "Atari 7800" },
    { ATARI_800, "Atari 800" },
    { ATARI_JAGUAR, "Atari Jaguar" },
    { ATARI_JAGUAR_CD, "Atari Jaguar CD" },
    { ATARI_LYNX, "Atari Lynx" },
    { ATARI_ST, "Atari ST/STE/Falcon" },
    { ATARI_XE, "Atari XE" },
    { COLECOVISION, "Colecovision" },
    { COMMODORE_64, "Commodore 64" },
    { INTELLIVISION, "Intellivision" },
    { MAC_OS, "Macintosh" },
    { MSX, "MSX" },
    { NEOGEO, "NeoGeo" },
    { NEOGEO_POCKET, "NeoGeo Pocket" },
    { NEOGEO_POCKET_COLOR, "NeoGeo Pocket Color" },
    { NINTENDO_3DS, "Nintendo 3DS" },
    { NINTENDO_64, "Nintendo 64" },
    { NINTENDO_DS, "Nintendo DS" },
    { NINTENDO_GAMECUBE, "Nintendo GameCube" },
    { NINTENDO_GAME_BOY, "Game Boy" },
    { NINTENDO_GAME_BOY_ADVANCE, "Game Boy Advanced" },
    { NINTENDO_GAME_BOY_COLOR, "Game Boy Color" },
    { NINTENDO_NES, "Nintendo Entertainment System" },
    { NINTENDO_SNES, "Super Nintendo Entertainment System" },
    { NINTENDO_SWITCH, "Nintendo Switch" },
    { NINTENDO_WII, "Nintendo Wii" },
    { NINTENDO_WII_U, "Nintendo WiiU" },
    { PC, "PC" },
    { PLAYSTATION, "Playstation" },
    { PLAYSTATION_2, "Playstation 2" },
    { PLAYSTATION_3, "Playstation 3" },
    { PLAYSTATION_4, "Playstation 4" },
    { PLAYSTATION_PORTABLE, "Playstation Portable" },
    { PLAYSTATION_VITA, "Playstation Vita" },
    { SEGA_32X, "Sega 32X" },
    { SEGA_CD, "Sega CD" },
    { SEGA_DREAMCAST, "Dreamcast" },
    { SEGA_GAME_GEAR, "Game Gear" },
    { SEGA_GENESIS, "Sega Genesis" },
    { SEGA_MASTER_SYSTEM, "Sega Master System" },
    { SEGA_MEGA_DRIVE, "Sega Mega Drive" },
    { SEGA_SATURN, "Sega Saturn" },
    { TURBOGRAFX_16, "TurboGrafx-16 / PC Engine" },
    { WONDERSWAN, "Wonderswan" },
    { WONDERSWAN_COLOR, "Wonderswan Color" },
    { XBOX, "Xbox" },
    { XBOX_360, "Xbox 360" },
    { XBOX_ONE, "Xbox One" },
    { ZX_SPECTRUM, "ZX Spectrum" },
};

QString longName(Id id) {
    return long_names.value(id, "");
}

} // namespace Platforms
